"""add rating field to books

Revision ID: 54038286a3b6
Revises: b6811994a8b4
Create Date: 2026-03-14 15:21:16.419818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54038286a3b6'
down_revision: Union[str, Sequence[str], None] = 'b6811994a8b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('rating', sa.Float(), nullable=True, comment='Средний рейтинг из Open Library'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'rating')
    # ### end Alembic commands ###
